/**
 * Default scenario values and form defaults.
 */
export const DEF = {
  employment: 36000,
  zzpIncome: 0,
  hasPartner: false,
  inc2: 0,
  pensioenPerc: 5,
  isAOW: false,
  hasKids: false,
  nKids: 1,
  kidsU12: 1,
  nKidsOpvang: 0,
  kotUur: 9.5,
  kotUren: 100,
  isRenter: true,
  rent: 750,
  hasHome: false,
  hypotheek: 250000,
  rentePerc: 3.8,
  wozWaarde: 350000,
  isStarter: false,
  urenOK: true,
  duoSchuld: 0,
  provincie: "Noord-Holland",
  box2Income: 0,
  box3Spaargeld: 0,
  box3Beleggingen: 0,
  box3Schulden: 0,
  wwwiaIncome: 0,
  hasVolWW: false,
  hasVolWIA: false,
  alimentatieBetaald: 0,
  alimentatieOntvangen: 0,
  lijfrentePremie: 0,
  gemCategorie: "midden",
};
